apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basicauth
  template:
    metadata:
      labels:
        app: basicauth 
    spec:
      containers:
      - name: basicauth-index-container
        image: yegekucuk2/index:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basicauth-service
spec:
  selector:
    app: basicauth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basicauth-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "basicauth-secret"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - local.basicauthtest.com"
spec:
  rules:
  - host: local.basicauthtest.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: basicauth-service
            port:
              number: 80
